import Foundation

struct BrandManager {
    static let shortcut = BrandInfo(
        assetFolderName: "shortcut",
        name: "name",
        productName: "productName",
        submitButtonText: "submitButtonText", 
        selectLanguageTitle: "selectLanguageTitle",
        selectedLanguage: "selectedLanguage",
        additionalLanguages: [
            "language 1",
            "language 2",
            "language 3",
            "language 4",
            "language 5",
            "language 6",
            "language 7",
            "language 8"
        ],
        registerProductText: "registerProductText",
        subheading: "subheading",
        userManualText: "userManualText",
        specificationsText: "specificationsText",
        productInformationText: "productInformationText",
        sparePartsText: "sparePartsText",
        customerFeedbackText: "customerFeedbackText",
        notificationText: "notificationText",
        userManualTitleText: "userManualTitleText",
        userManualProductOverViewText: "userManualProductOverViewText",
        userManualBeforeUseText: "userManualBeforeUseText",
        userManualUserGuideText: "userManualUserGuideText",
        userManualCleaningText: "userManualCleaningText",
        userManualProductOverviewHeaderText: "userManualProductOverviewHeaderText",
        userManualProductComponentHeaderText: "userManualProductComponentHeaderText",
        userManualUserGuideViewHeaderText: "userManualUserGuideViewHeaderText",
        userManualCleaningViewHeaderText: "userManualCleaningViewHeaderText",
        specsHeaderText: "specsHeaderText",
        productInfoHeaderText: "productInfoHeaderText",
        productInfoSubtitle1: "productInfoSubtitle1",
        productInfoBodyText1: "productInfoBodyText1",
        productInfoSubtitle2: "productInfoSubtitle2",
        productInfoBodyText2: "productInfoBodyText2",
        productInfoVideoURL: URL(string: "https://www.youtube.com/watch?v=kIq9v_d2B34"),
        subProduct1Title: "subProduct1Title",
        subProduct1Detail: "subProduct1Detail",
        subProduct1Price: "subProduct1Price",
        subProduct2Title: "subProduct2Title",
        subProduct2Detail: "subProduct2Detail",
        subProduct2Price: "subProduct2Price",
        subProduct3Title: "subProduct3Title",
        subProduct3Detail: "subProduct3Detail",
        subProduct3Price: "subProduct3Price",
        subProduct4Title: "subProduct4Title",
        subProduct4Detail: "subProduct4Detail",
        subProduct4Price: "subProduct4Price",
        customerFeedbackHeaderText: "customerFeedbackHeaderText",
        customerFeedbackNameTextFieldPlaceholder: "customerFeedbackNameTextFieldPlaceholder",
        customerFeedbackTextEditorTitleText: "customerFeedbackTextEditorTitleText",
        customerFeedbackSubmitButtonText: "customerFeedbackSubmitButtonText",
        customerFeedbackAlertTitle: "customerFeedbackAlertTitle",
        customerFeedbackAlertMessage: "customerFeedbackAlertMessage",
        registerProductCountryTitle: "registerProductCountryTitle",
        registerProductCountry: "registerProductCountry",
        registerProductSerialNumberText: "registerProductSerialNumberText",
        registerProductProductText: "registerProductProductText",
        registerProductNamePlaceholderText: "registerProductNamePlaceholderText",
        registerProductEmailPlaceholderText: "registerProductEmailPlaceholderText",
        registerProductAlertTitle: "registerProductAlertTitle",
        registerProductAlertText: "registerProductAlertText"
    )

    static let aarke = BrandInfo(
        assetFolderName: "aarke",
        name: "Aarke",
        productName: "Aarke Carbonator 3",
        submitButtonText: "SKICKA",
        selectLanguageTitle: "Velg Språk:",
        selectedLanguage: "Svenska",
        additionalLanguages: [
            "Finska",
            "Danska",
            "Norska",
            "Tyska",
            "Engelska",
            "Spanska",
            "Islandska"
        ],
        registerProductText: "Registrera Produkt",
        subheading: "Wälkommen til Aarke",
        userManualText: "Bruksanvisning",
        specificationsText: "Specifikationer",
        productInformationText: "Produktinformation",
        sparePartsText: "Reservdelar",
        customerFeedbackText: "Recensioner",
        notificationText: "Registrer din Carbonator 3 nå 🥳",
        userManualTitleText: "BRUKSANVISNING",
        userManualProductOverViewText: "Förpackningens innehåll",
        userManualBeforeUseText: "Produktens komponenter",
        userManualUserGuideText: "Installation av kollsyrepatron",
        userManualCleaningText: "Kolsyra vatten",
        userManualProductOverviewHeaderText: "Förpackningens innehåll",
        userManualProductComponentHeaderText: "Produktens komponenter",
        userManualUserGuideViewHeaderText: "Installation av kollsyrepatron",
        userManualCleaningViewHeaderText: "Kolsyra vatten",
        specsHeaderText: "SPECIFIKATIONER",
        productInfoHeaderText: "PRODUKTINFORMATION",
        productInfoSubtitle1: "CARBONATOR 3",
        productInfoBodyText1: "Carbonator 3 is a premium sparkling water maker in stainless steel. It’s built to last and comes in several.....",
        productInfoSubtitle2: "Best i test",
        productInfoBodyText2: "Aarke Carbonator 3 is built to last. With an obsession for detail and hones....",
        productInfoVideoURL: URL(string: "https://www.youtube.com/embed/zbCxs5Mx8rc"),
        subProduct1Title: "POLERDUK",
        subProduct1Detail: "Reservedel WSPL-3B",
        subProduct1Price: "99,-",
        subProduct2Title: "DROPPFATS-GALLER",
        subProduct2Detail: "Reservedel WSPL-3B",
        subProduct2Price: "139,-",
        subProduct3Title: "STÅLKORK TIL PET-FLASKE",
        subProduct3Detail: "Reservedel WSPL-3B",
        subProduct3Price: "199,-",
        subProduct4Title: "GUMMI PACKNING",
        subProduct4Detail: "Reservedel WSPL-3B",
        subProduct4Price: "99,-",
        customerFeedbackHeaderText: "RECENSIONER",
        customerFeedbackNameTextFieldPlaceholder: "NAMN",
        customerFeedbackTextEditorTitleText: "BESKRIV",
        customerFeedbackSubmitButtonText: "SKICKA",
        customerFeedbackAlertTitle: "Tusen Takk!",
        customerFeedbackAlertMessage: "Din tilbakemelding vil bli behandlet fortløpende.", 
        registerProductCountryTitle: "Land",
        registerProductCountry: "Sverige",
        registerProductSerialNumberText: "Serienummer:",
        registerProductProductText: "Produkt:",
        registerProductNamePlaceholderText: "NAMN",
        registerProductEmailPlaceholderText: "E-MAIL",
        registerProductAlertTitle: "Produktet er nå registrert!",
        registerProductAlertText: "Du vil nå kunne dra nytte av fordelene ved å registere produktet ditt"
    )

    static let wilfa = BrandInfo(
        assetFolderName: "wilfa",
        name: "Wilfa",
        productName: "Wilfa Performance",
        submitButtonText: "Send Inn",
        selectLanguageTitle: "Velg språk:",
        selectedLanguage: "Norge",
        additionalLanguages: [
            "Finsk",
            "Dansk",
            "Svensk",
            "Tysk",
            "Engelsk",
            "Spansk",
            "Islandsk"
        ],
        registerProductText: "Registrer kaffetrakter",
        subheading: "Hva kan vi hjelpe med",
        userManualText: "Brukermanual",
        specificationsText: "Spesifikasjoner",
        productInformationText: "Produkt Informasjon",
        sparePartsText: "Reservedeler",
        customerFeedbackText: "Kundeomtaler",
        notificationText: "Notification",
        userManualTitleText: "Brukermanual",
        userManualProductOverViewText: "Produktoversikt",
        userManualBeforeUseText: "Før bruk",
        userManualUserGuideText: "Bruk",
        userManualCleaningText: "Rengjøring og vedlikehold",
        userManualProductOverviewHeaderText: "Produktoversikt",
        userManualProductComponentHeaderText: "Før Bruk",
        userManualUserGuideViewHeaderText: "Bruk",
        userManualCleaningViewHeaderText: "Rengjøring og vedlikehold",
        specsHeaderText: "Spesifikasjoner",
        productInfoHeaderText: "Produkt informasjon",
        productInfoSubtitle1: "Performance\nKaffetrakter",
        productInfoBodyText1: "Best i test kaffetrakter Performance er ikke bare en ny kaffetrakter - det er kaffetrakteren som er utviklet i Norge.",
        productInfoSubtitle2: "Best i test",
        productInfoBodyText2: "Performance ble best i test hos tek.no sin siste kaffetraktertest",
        productInfoVideoURL: URL(string: "https://www.youtube.com/watch?v=s0F10F0a8GA"),
        subProduct1Title: "Performance kanne med lokk",
        subProduct1Detail: "Reservedel WSPL-3B",
        subProduct1Price: "300,-",
        subProduct2Title: "Performance lokk vanntank",
        subProduct2Detail: "Reservedel WSPL-3B",
        subProduct2Price: "199,-",
        subProduct3Title: "Performance kanne til filterholder",
        subProduct3Detail: "Reservedel WSPL-3B",
        subProduct3Price: "199,-",
        subProduct4Title: "Performance filterholder med lokk",
        subProduct4Detail: "Reservedel WSPL-3B",
        subProduct4Price: "299,-",
        customerFeedbackHeaderText: "Kundeomtale",
        customerFeedbackNameTextFieldPlaceholder: "Navn",
        customerFeedbackTextEditorTitleText: "Omtale",
        customerFeedbackSubmitButtonText: "Send inn",
        customerFeedbackAlertTitle: "Alert title",
        customerFeedbackAlertMessage: "Alert message", 
        registerProductCountryTitle: "Land",
        registerProductCountry: "Norge",
        registerProductSerialNumberText: "1242",
        registerProductProductText: "Wilfa Performance",
        registerProductNamePlaceholderText: "Navn",
        registerProductEmailPlaceholderText: "E-Mail",
        registerProductAlertTitle: "Produktet er nå registrert!",
        registerProductAlertText: "Du vil nå kunne dra nytte av fordelene ved å registere produktet ditt"
    )
}
